[package]
name = "pbinspect"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.6.11", features = ["csr", "nightly"] }
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "0.3.69", features = ["Clipboard", "ClipboardItem", "Navigator"] }
